### ISSUE TITLE
Add search feature.

### ISSUE THREAD

**Issue by joakin** [joakin/loot-ui#13]
Use MobileFrontend's inspired workflow (toolbar with icon opens search overlay).

Use transient (History replace) urls like `/search/:term`.

**Comment by joakin** [comment]
Depends on https://github.com/joakin/loot/issues/30

**Comment by joakin** [comment]
Search merged in https://github.com/joakin/loot-ui/pull/20

Improvements in https://github.com/joakin/loot-ui/pull/22

**Comment by phuedx** [comment]
Both #20 and #22 have been merged.
