### ISSUE TITLE
Lazy loading images does not work in Safari

### ISSUE THREAD

**Issue by joakin** [joakin/loot-ui#17]
Neither desktop nor iPhone.

Probably a thing with getClientRectBounds or the scrollY or window.innerHeight in  https://github.com/joakin/loot-ui/blob/master/lib/client/components/lazy-images/index.js#L34-L49

**Comment by joakin** [comment]
It's not that lazy loading doesn't work, but that the JS crashes in a way that the debugger closes if you try to debug so it's impossible to know why, so you get the HTML only version (without images).

Adding the es6 shims fixes it, see https://github.com/joakin/loot-ui/pull/27

**Comment by jdlrobson** [comment]
Looks fixed to me! Verified on https://reading-web-research.wmflabs.org/

**Comment by joakin** [comment]
Thanks for verifying!
