### ISSUE TITLE
`npm test:watch` doesn't work

### ISSUE THREAD

**Issue by joakin** [joakin/loot-ui#23]
Meaning it starts, but after a file change it doesn't re-run the tests, and stops watching.

**Comment by joakin** [comment]
The problem seems to be with `babel-core/register` not with our wrapping script:

```
loot-ui (master %=) $ mocha --compilers js:babel-core/register -w lib/**/__tests__/*.js

  Array
    #indexOf()
      ✓ should return -1 when the value is not present


  1 passing (102ms)



  0 passing (0ms)
```

**Comment by joakin** [comment]
Nope, the problem is mocha. Requiring mocha's functions instead of using globals breaks the watcher.

```
import { describe, it } from 'mocha'
```

See https://github.com/mochajs/mocha/issues/1847

We shall investigate using an external watcher, like nodemon or [npm-watch](https://www.npmjs.com/package/npm-watch) for the moment.

Having global variables screws with the linter.

**Comment by joakin** [comment]
External watchers are a lot slower, a file change reruns a test in 1ms, while with nodemon it takes 100ms. It really makes a difference.

I've come up with a workaround, instead of `import`ing mocha variables, we'll just destructure them from the global namespace, and that's how we'll write the tests and keep the linter happy.

Something like this works fine:

``` js
import assert from 'assert'
const { describe, it } = global

describe('Array', function () {
  describe('#indexOf()', function () {
    it('should return -1 when the value is not present', function () {
      assert.equal(-1, [1, 2, 3].indexOf(5))
      assert.equal(-1, [1, 2, 3].indexOf(0))
    })
  })
})
```

**Comment by joakin** [comment]
@phuedx Close when you read this (as acknowledgement)!

**Comment by phuedx** [comment]
![boom](http://media3.giphy.com/media/H6jVFw6KGRNmM/giphy.gif)
