### ISSUE TITLE
Various pages inaccessible

### ISSUE THREAD

**Issue by jdlrobson** [joakin/loot-ui#28]
Visit https://en.m.wikipedia.org/wiki/Ky%C5%ABsh%C5%AB

Visit http://reading-web-research.wmflabs.org/wiki/Ky%C5%ABsh%C5%AB
I get {"type":"https://restbase.org/errors/not_found#page_revisions","title":"Not found.","method":"get","detail":"Page or revision not found.","uri":"/en.wikipedia.org/v1/page/html/Kykshk"}

Visit http://reading-web-research.wmflabs.org/wiki/Euclid's%20algorithm
Blank page.

Issue in Parsoid or loot?

**Comment by joakin** [comment]
Seems a restbase problem https://en.wikipedia.org/api/rest_v1/page/html/Ky%C5%ABsh%C5%AB

**Comment by jdlrobson** [comment]
This gets fixed by the above - not sure if you want to handle in a better way! And feel free to tweak if my code styling is not to your satisfaction - couldn't work out how to beautify.

**Comment by joakin** [comment]
Lol I didn't see the examples here and was testing with http://reading-web-research.wmflabs.org/api/slim/Fecal haha :joy: Anyway, fixed.
