### ISSUE TITLE
Read more should happen automatically

### ISSUE THREAD

**Issue by jdlrobson** [joakin/loot-ui#42]
When I scroll down the article it should expand automatically without me doing anything.
Expansion should happen when I've scrolled through 10% of the initial article length.
We should minimise the reader noticing that this is happening.

**Comment by joakin** [comment]
I hesitate to change this for now. After the summit when this is not in a
goal we can explore the different strategies and do what we think is best.

I would personally trigger the load of the full article automatically as
soon as we have rendered the summary one, as google web lite or however is
called does.

But yes, personally agreed, we'll explore this later.

**Comment by joakin** [comment]
I've implemeted this as part of https://github.com/joakin/loot-ui/pull/51

It would be easily reversible if needed.
